set allow-duplicate-recipes := true
set ignore-comments := true

_default:
	@just --list

# Imports
import "/usr/share/wepos/just/coolercontrol.just"
import "/usr/share/wepos/just/flatpaks.just"
import "/usr/share/wepos/just/git.just"
import "/usr/share/wepos/just/homebrew.just"
import "/usr/share/wepos/just/keyboard.just"
import "/usr/share/wepos/just/nerd-fonts.just"
import "/usr/share/wepos/just/plasma.just"
import "/usr/share/wepos/just/starship.just"
import "/usr/share/wepos/just/theme.just"
