# Load kernel modules for CoolerControl to give it access to motherboard headers

# Info about the kernel module for ASUS motherboards
# https://github.com/lm-sensors/lm-sensors/issues/416#issuecomment-2359409670

# ASUS ROG Strix B650E-F Gaming Wifi
nct6775
